image:
  file: /docker/devcontainer/.devcontainer/Dockerfile

tasks:
  - name: Setup Kaldi + SRILM
    init: |
      # Make scripts executable
      chmod +x /mhscripts/*.sh

      # Run the setup script to install SRILM and configure Kaldi
      /mhscripts/nb7_setup_kaldi.sh

      # Optionally, you could remove the setup script here if it's no longer needed
      # rm /mhscripts/nb7_setup_kaldi.sh
    command: |
      # After setup, keep the terminal open for further commands
      bash
